import Header from "./components/Header";
import "./globals.css";
import {
  Montserrat,
  Roboto,
  Playfair_Display,
  Fira_Sans,
} from "next/font/google";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
